libshvcoreqt/src/log.h
uz jsi to jednou mergeoval v masteru, ted jsem to pridal jeste do ccpcp
=> improved logging of QT types

libshvchainpack/c/cchainpack.c
Signed-off-by: Pavel Pisa <ppisa@pikron.com>
=> Further optimization of significant_bits_part_length for GCC.

libshvcore/src/utils/fileshvjournal.cpp
Jsem si dovolil takový malý merge request pro zprovoznění kompilace v MAC OS.
=> add definition for mac os environment for mkdir function

libshvbroker/src/appclioptions.cpp
=> add protocol type

utils/cpmerge/cpmerge.pro, utils/cpmerge/main.cpp, utils/utils.pro
=> Cpon merge

utils/cpmerge/main.cpp
=> fix override existing key

libshviotqt/src/rpc/rpcresponsecallback.cpp
Same as https://github.com/silicon-heaven/libshv/pull/188
=> shv3 branch: libshviotqt: RpcCall: delete after maybeResult slots

CMakeLists.txt
It needs to put after -Wconversion, otherwise it doesn't do anything.
=> Fix -Wno-sign-conversion flag

libshvcore/src/utils/crypt.h
=> fix shvcore::utils::crypt include

libshvchainpack/c/ccpon.c, libshvchainpack/c/tests/test_ccpcp.c, libshvcore/src/utils/shvtypeinfo.cpp
=> Fix warnings

libshvvisu/src/svgscene/saxhandler.h
Qt compiled from git needs this for Q_DECLARE_METATYPE.
=> Fix include for newer Qt

libshvvisu/src/logview/dlgloginspector.cpp, libshvvisu/src/logview/dlgloginspector.h, libshvvisu/src/logview/dlgloginspector.ui
=> add loadData to logInspector (cpon, chainpack)

libshvvisu/src/logview/dlgloginspector.cpp, libshvvisu/src/logview/dlgloginspector.h, libshvvisu/src/logview/dlgloginspector.ui
Reverts silicon-heaven/libshv#249
=> Revert "add loadData to logInspector (cpon, chainpack)"

libshvvisu/src/logview/dlgloginspector.cpp, libshvvisu/src/logview/dlgloginspector.h, libshvvisu/src/logview/dlgloginspector.ui
Reverts silicon-heaven/libshv#251
=> Revert "Revert "add loadData to logInspector (cpon, chainpack)""

libshvchainpack/src/chainpack/rpcvalue.cpp, libshvchainpack/tests/test_chainpack.cpp
In terms of speed, they're equivalent.
=> libshvchainpack: Rewrite typeForName

libshvbroker/src/brokerapp.cpp, libshvbroker/src/currentclientshvnode.cpp, libshvbroker/src/rpc/masterbrokerconnection.cpp, libshvchainpack/CMakeLists.txt, libshvchainpack/src/chainpack/accessgrant.cpp, libshvchainpack/src/chainpack/accessgrant.h, libshvchainpack/src/chainpack/metamethod.cpp, libshvchainpack/src/chainpack/metamethod.h, libshvchainpack/tests/test_accessgrant.cpp, libshviotqt/src/node/shvnode.cpp
access level is taken from most powerfull one
role 'dot_local' is privilege to access `.local` node in shv subtree
=> access grant can have more roles

.github/actions/run-linter/action.yml
I'm using the "_" env var and the --verbose option to show how many files are remaining.
=> CI: linters: Show progress

libshvbroker/include/shv/broker/ldap/ldap.h, libshvbroker/src/aclmanager.cpp, libshvbroker/src/aclmanager.h, libshvbroker/src/appclioptions.cpp, libshvbroker/src/appclioptions.h, libshvbroker/src/brokeraclnode.cpp, libshvbroker/src/brokeraclnode.h, libshvbroker/src/brokerapp.cpp, libshvbroker/src/brokerapp.h, libshvbroker/src/ldap.cpp, libshvbroker/src/ldapconfig.h, libshvbroker/src/rpc/clientconnectiononbroker.cpp
ClientConnectionOnBroker might get deleted before we're done with LDAP.
=> LDAP improvements

libshvbroker/src/brokerappnode.cpp
=> add SHV_VERSION and SHV_GIT_COMMIT to broker node

libshvchainpack/src/chainpack/rpcdriver.cpp
When e.pos() is at the end of the string or less than size of the left context (10*16), the `pos` argument of data.substr() overflows and triggers std::out_of_range exception.
=> RpcDriver: fix overflow in ParseException handler

libshviotqt/src/node/shvnode.cpp
=> hel002 fix log flood

libshvvisu/src/timeline/graphwidget.cpp
=> Rename to Reset channels to defaults

CMakeLists.txt, libshvbroker/CMakeLists.txt, libshvchainpack/CMakeLists.txt, libshvchainpack/c/CMakeLists.txt, libshvcore/CMakeLists.txt, libshvcoreqt/CMakeLists.txt, libshviotqt/CMakeLists.txt, libshvvisu/CMakeLists.txt
As per https://stackoverflow.com/a/5379238
=> cmake: Fix installing export multiple times

libshvvisu/include/shv/visu/timeline/graph.h, libshvvisu/src/timeline/graph.cpp
Reverts silicon-heaven/libshv#515
didn't add QtSvg to dependencies
=> Revert "draw graph into SVG"

libshvchainpack/include/shv/chainpack/rpcvalue.h, libshvchainpack/src/rpcvalue.cpp
asData is gone, let's get rid of this one too.
=> Remove asBytes

libshvbroker/CMakeLists.txt, libshvbroker/include/shv/broker/brokerapp.h, libshvbroker/src/brokeraclnode.cpp, libshvbroker/src/brokerapp.cpp, libshvbroker/src/brokerappnode.cpp, libshvbroker/src/dotbrokernode.cpp, libshvbroker/src/dotbrokernode.h
Step towards compatibility with SHV3.
This also removes/replaces currently not working .broker/mounts node.
https://silicon-heaven.github.io/shv-doc/rpcmethods/broker.html#brokermounts
=> Add .broker::mounts and .broker::mountedClientInfo methods

libshviotqt/include/shv/iotqt/rpc/socket.h, libshviotqt/src/rpc/localsocket.cpp, libshviotqt/src/rpc/serialportsocket.cpp, libshviotqt/src/rpc/socket.cpp, libshviotqt/src/rpc/websocket.cpp
Fixes: https://github.com/silicon-heaven/shvspy/issues/70
=> Fix localsocket crash

libshviotqt/src/rpc/localsocket.cpp
For Qt 6.6.3 android toolchain
=> Fix Android build
