libshvchainpack/js-export/bint.js, libshvchainpack/js-export/chainpack.js, libshvchainpack/js-export/cpcontext.js, libshvchainpack/js-export/cpon.js, libshvchainpack/js-export/rpcmessage.js, libshvchainpack/js-export/rpcvalue.js
When javascript is compiled class names are changed and constructor.name returns rubish.
=> use instanceof instead constructor.name which may be modified

libshvbroker/src/rpc/brokertcpserver.cpp
With Qt 5.14.1 the build fails on `‘errorOccurred’ is not a member of ‘QSslSocket’`.
However, it passes with Qt 5.15.1.
=> libshvbroker: fix signal identifier to pass build with older Qt version

libshvbroker/src/rpc/brokertcpserver.cpp
QAbstractSocket::errorOccurred is introduced in version 5.15.0.
Use QAbstractSocket::error with older versions.
=> libshvbroker: handle undefined signal in older Qt versions

libshvbroker/src/appclioptions.cpp, libshvbroker/src/appclioptions.h, libshvbroker/src/rpc/brokertcpserver.cpp
Pass all certificate files in single "ssl.certs" config option.
Load all certificates contained in a single certificate file.
=> libshvbroker: fix certificate chain loading

libshviotqt/include/shv/iotqt/node/filenode.h, libshviotqt/src/node/filenode.cpp, libshviotqt/src/node/filenode.h, libshviotqt/src/node/localfsnode.cpp, libshviotqt/src/node/localfsnode.h, libshviotqt/src/node/node.pri
FileNode represents common interface to both files on local
filesystem and virtual files existing only in an application.
The interface provides read-only methods. Any more methods
can be added in subclasses (LocalFSNode).
=> libshviotqt: introduce FileNode

libshvchainpack/c/cchainpack.c
Masked value assignment to bool may result in undefined behaviour on some platforms (Cortex M7 on NuttX) and thus return incorrect integer value. This commit moves the negative check to if statement.
=> libshvchainpack/c/chainpack.c: do not use masked value assignment bool

libshvbroker/src/brokerapp.cpp
Before this, SIGHUP as a reloading mechanism. SIGHUP triggers when the
parent terminal quits, so the child process should also quit. The reload
mechanism now uses SIGUSR11.
Fixes: #176
=> libshvbroker: Use SIGUSR1 for reloading

libshviotqt/src/node/shvnode.h
ShvNode::shvPath() returns by value, so this include is needed,
otherwise the user of the shvnode.h has to include it.
=> libshviotqt: Include shvpath

libshviotqt/src/node/shvnode.h
Found by Clang.
/home/vk/git/shv/3rdparty/libshv/libshvchainpack/include/shv/chainpack/../../../src/chainpack/accessgrant.h:60:1: warning: 'AccessGrant' defined as a struct here but previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags] struct SHVCHAINPACK_DECL_EXPORT AccessGrant
^
/home/vk/git/shv/3rdparty/libshv/libshviotqt/include/shv/iotqt/node/../../../../src/node/shvnode.h:17:28: note: did you mean struct here? namespace shv::chainpack { class AccessGrant; }
=> Fix declaring a struct as class

libshvcore/include/shv/core/utils/abstractshvjournal.h, libshvcore/src/utils/abstractshvjournal.h
Need it for the reimplementation of getLog.
=> Make AbstractShvJournal::addToSnapshot public

libshvchainpack/src/chainpack/rpcvalue.cpp, libshvchainpack/src/chainpack/rpcvalue.h
RpcValue doesn't really care about the size of the integer, it only cares about signedness. Having fixed width integer constructors meant that on some platforms (arm/wasm), they were ambiguous. Example, on ARM:
1) `long int` is 32 bit
2) `int` is also 32 bit
3) `int32_t` is typedefed to `int`, so this ctor can't be used for `long
int`
4) this makes the Int/UInt ctors ambiguous for `long int`
Fix this by created constructors for all integer types.
=> Fix ambiguous RpcValue::Int/UInt ctors

CMakeLists.txt
GCC is too annoying about shadowing field by ctor parameters and private fields of base classes by local variables.
=> cmake: gcc: Turn on -Wshadow=local

libshvcoreqt/CMakeLists.txt, libshvcoreqt/src/utils.cpp, libshvcoreqt/src/utils.h, libshvcoreqt/tests/test_join_path.cpp
Joining paths is always a pain, when you have a mix of QString and std::string. This patch adds a special templated function, that's able automatically convert the input strings into the desired result value.
=> libshvcoreqt: Improve joinpath

libshvchainpack/c/ccpcp.c, libshvchainpack/c/ccpcp.h, libshvchainpack/c/ccpcp_convert.c, libshvchainpack/c/ccpon.c, libshvchainpack/c/tests/test_ccpcp.c
To measure buffer size needed to pack use ccpcp_pack_context_dry_run_init() Packed size can be found in ccpcp_pack_context::bytes_written field
For example see: test_dry_run_int() in test_ccpcp.c
=> Add support for NULL chainpack serialization buffer #202

libshvcoreqt/src/utils.cpp
WASM doesn't have this it seems.
=> Fix build error when ranges are not available

libshvchainpack/c/ccpcp.c
/home/vk/git/eyas/3rdparty/libshv/libshvchainpack/c/ccpcp.c:24:42: runtime error: applying zero offset to null pointer
*0 0x5591d2108aa3 in ccpcp_pack_context_init /home/vk/git/eyas/3rdparty/libshv/libshvchainpack/c/ccpcp.c:24:42
*1 0x5591d210918e in ccpcp_pack_context_dry_run_init /home/vk/git/eyas/3rdparty/libshv/libshvchainpack/c/ccpcp.c:37:2
*2 0x5591d20fb242 in test_dry_run_cpon /home/vk/git/eyas/3rdparty/libshv/libshvchainpack/c/tests/test_ccpcp.c:375:3
*3 0x5591d20fad1f in test_cpons /home/vk/git/eyas/3rdparty/libshv/libshvchainpack/c/tests/test_ccpcp.c:672:3
*4 0x5591d20fc4fe in main /home/vk/git/eyas/3rdparty/libshv/libshvchainpack/c/tests/test_ccpcp.c:769:2
*5 0x7f345b82078f  (/usr/lib/libc.so.6+0x2378f) (BuildId: 4a4bec3d95a1804443e852958fe59ed461135ce9)
*6 0x7f345b820849 in …
=> Fix undefined behavior

libshvchainpack/c/ccpon.c
The variable is passed to civil_from_days that accepts int but was defined as int32.
=> libshvchainpack/c/ccpon: fix warning about passing invalid type

libshvbroker/src/brokerapp.cpp
Without the return, we would call cb(result), which is not what we want (because the LDAP auth would be completely bypassed.
=> ldap: Add missing return

.github/actions/cmake/action.yml, .github/workflows/run-tests.yml
Linter workflows would choke as soon as ldap.{cpp,h} changes. Also, generally, I'd like the ldap code to be checked. Hopefully the LDAP code builds with Qt5 (no reason it shouldn't imho).
=> CI: Always build with LDAP, even for linters

libshvbroker/src/aclmanager.cpp, libshvbroker/src/currentclientshvnode.cpp, libshvbroker/src/tunnelsecretlist.cpp, libshviotqt/src/node/filenode.cpp, libshviotqt/src/rpc/clientconnection.cpp, libshviotqt/src/utils.cpp
`QCryptographicHash::addData` uses `QByteArray` for versions prior to QT 6.3. Therefore the current check `QT_VERSION_MAJOR >= 6` is not sufficient and build results in error if QT 6.2 (in long term Ubuntu 22.04 for example) is used. This commit adds additional condition `QT_VERSION_MINOR >= 3`.
=> libshv: use QByteArray in QCryptographicHash::addData for QT prior to 6.3

libshvcore/src/utils/versioninfo.cpp
Qt for Android 6.5.0 does not have <=> for tuple :(
```c++
/home/vk/git/eyas/3rdparty/libshv/libshvcore/src/utils/versioninfo.cpp:40:81: error: invalid operands to binary expression ('tuple<const int &, const int &, const int &>' and 'tuple<const int &, const int &, const int &>')
return std::tie(this->m_majorNumber, this->m_minorNumber, this->m_patchNumber) <=> std::tie(v.m_majorNumber, v.m_minorNumber, v.m_patchNumber);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Fix VersionInfo::operator<=> for Android

libshvbroker/src/brokerapp.cpp
```
AutoMoc: /home/vk/git/shvspy/3rdparty/libshv/libshvbroker/src/brokerapp.cpp:0:1: note: No relevant classes found. No output generated.
```
The warning might be confusing, and someone might accidentally remove the line. It is needed when building with LDAP.
=> Remove "warning" when building without LDAP

libshvcore/src/utils/shvfilejournal.cpp
On different platforms, std::basic_istream<char>::pos_type could be various types, like long and long long.
=> Fix casting fpos

libshvbroker/src/brokerapp.cpp, libshvbroker/src/brokerapp.h, libshvbroker/src/rpc/clientconnectiononbroker.cpp
And only for plaintext password. Clients should send plaintext password only with SSL, so suggesting users use it is valid.
=> libshvbroker: Don't check for SSL

libshviotqt/src/rpc/clientconnection.cpp
The previous syntax was valid, but didn't work in clang. :(
=> Fix emplace_back for clang

libshvcoreqt/CMakeLists.txt
qt_add_library() already does this. The reason we did this manually is because we used just plain add_library() before.
=> Remove UNICODE definitions

libshvchainpack/src/chainpack/rpcdriver.cpp
Displays a helpful information for debugging without the need to have a too verbose RpcData log level turned on.
=> rpcdriver: log all received data on ParseException

libshviotqt/CMakeLists.txt
Having this unconditionally can lead to linking errors, if you have websockets disabled.
This is with `WITH_SHV_WEBSOCKETS=OFF`
```
C:/mingw-12/x86_64-12.1.0-release-posix-seh-rt_v10-rev3/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\libshviotqt.dir/objects.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3shv5iotqt3rpc9WebSocketE[_ZTVN3shv5iotqt3rpc9WebSocketE]+0x70): undefined reference to `shv::iotqt::rpc::WebSocket::connectToHost(QUrl const&)'
```
=> libshviotqt: Do not add websocket.h always

libshvcore/include/shv/core/utils.h, libshvcore/src/utils.cpp, libshvcore/tests/test_utils.cpp
I rewrote the `shv::core::utils::joinPath` function to use a fold expression instead of a recursive resolving. The intention was to improve these things:
1) Remove the unnecessary recursive calls.
Handling of variadic template arguments is usually handled via recursion, which means that the recursive variant of `joinPath` has to be called multiple times, until it encounters the single argument `joinPath` which only returns its argument. Using a fold expression removes recursion. _Note: the number of calls to the actual implementation of the `joinPath` algorithm is the same in both versions._
2) Disallow calling `joinPath` with zero and one argument.
This was impossible with the recursive version, because there had to be a one-arg `joinPath` overload to stop the recursion. The new version …
=> libshvcore: Rewrite utils::joinPath

libshvbroker/src/brokerapp.cpp
Fix for following error:
```
/home/vboxuser/FEL/shvspy/3rdparty/libshv/libshvbroker/src/brokerapp.cpp:751:20: error: 'class QFuture<QFuture<QJsonDocument> >' has no member named 'unwrap'
751 |                 }).unwrap().then(this, [this] (const QJsonDocument& json) {
```
Unwrap function is only available in QT v6.4 and after.
=> Build on qt 6.2

flake.nix
This fixes flake.nix for changes in
51bdd3fa9496952a867d4351ce289097397dfc78.
=> flake.nix: Fix enable of advanced features

libshvcore/src/utils/shvtypeinfo.cpp
=> Fix missing header

libshviotqt/src/node/localfsnode.cpp
... or reading with offsets resulting in zero-size result.
=> LocalFSNode: Allow reading empty files

libshvvisu/src/timeline/graph.cpp
on Android `QFont::pointSize() = -1`, at least sometimes
Documentation says:
```
int QFont::pointSize() const
Returns the point size of the font. Returns -1 if the font size was specified in pixels.
```
=> set font size by pixels if points are not available

libshvchainpack/c/include/shv/chainpack/compat.h
On my machine, ssize_t is defined in both sys/types.h and unistd.h, but it appears NuttX defines it only in sys/types.h. Try to solve this by also including sys/types.h
=> compat: Also try to find ssize_t in sys/types.h

libshvbroker/CMakeLists.txt, libshvbroker/src/appnode.cpp, libshvbroker/src/appnode.h, libshvbroker/src/brokerapp.cpp
I'm getting sick of having SHV3 clients ping all the time, and it working even though all the pings result in an error.
=> libshvbroker: Implement .app:ping

.github/workflows/test.yml
The new version of Nix no longer provides path to the source to the formatter and thus alejandra uses stdin instead and thus run fails.
https://github.com/NixOS/nix/pull/11438
=> github/workflows: fix Nix format check

libshvchainpack/src/rpcvalue.cpp
Casting bools to ints never makes sense. The reason I found is in the checkAlarms algorithm, where if you put a boolean as `value`, it could later be interpreted as a bitfield, because of this implicit conversion. It'll still do it now, but at least it won't result in `true` which will stop it from deducing invalid alarms.
=> RpcValue: Cast bools to ints as 0

libshviotqt/include/shv/iotqt/rpc/clientconnection.h, libshviotqt/include/shv/iotqt/rpc/rpccall.h, libshviotqt/src/rpc/clientconnection.cpp, libshviotqt/src/rpc/rpccall.cpp
This hopefully fixes a situation where:
- RpcCall obtains response metadata
- Frame gets obtained too
- parsing of the RpcMessage fails
- onRpcMessageReceived never gets called, which means that the RpcCall never completes
- the timeout for the RpcCall gets refreshed on every dataChunkReceived, even though these messages are not the ones RpcCall requests
Ideally, the &ClientConnection::dataChunkReceived signal would supply the slot with the request id of the chunk being received, but that's a bit too difficult to implement, because the Socket class does not remember the requests ids.
In the situation, where the frame fails to parse as a RpcMessage, there are two situations that can happen:
1) Another message never arrives. In this case, the RpcCall will eventually
timeout.
2) Another …
=> Fix RpcCall resetting on all data chunks

libshviotqt/CMakeLists.txt
It was needed in a previous implementation, but now it's unneeded.
=> oauth: Don't link with Gui

libshvbroker/src/brokeraclnode.cpp
No reason to go any lower - only the admin should be able to view this. We especially don't want passwords to be accessible with just rd.
=> Allow only admin to view/set broker acls
